name: 🚀 Alice Evo VM 自动部署

on:
  #schedule:
  #  - cron: '0 19 * * *' # UTC时间19:00 = 北京时间次日03:00
  # repository_dispatch:
  #   types: [service-down-alert]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      #  - name: 检查触发事件
      #    run: |
      #      echo "Workflow triggered by: ${{ github.event_name }}"
      #      if [[ "${{ github.event_name }}" == "repository_dispatch" ]]; then
      #        echo "触发事件类型 (Event Type): ${{ github.event.action }}"
      #        echo "收到来自 Uptime Kuma 的下线通知，开始执行自动唤醒流程..."
      #      elif [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
      #        echo "工作流被手动触发，开始执行唤醒..."
      #      else
      #        echo "工作流由计划任务触发，开始执行唤醒..."
      #      fi

      - name: ⬇️ 检出代码
        uses: actions/checkout@v4

      - name: 🛠️ 安装依赖 (jq, ssh)
        run: |
          sudo apt-get update
          sudo apt-get install -y jq ssh

      - name: 🔑 注入 SSH 私钥到 Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.ALICE_SSH_KEY }}

      - name: 🚀 自动部署 nodejs-argo
        id: deploy
        env:
          ALICE_CLIENT_ID: ${{ secrets.ALICE_CLIENT_ID }}
          ALICE_API_SECRET: ${{ secrets.ALICE_API_SECRET }}
          NODEJS_COMMAND: ${{ vars.NODEJS_COMMAND }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: |
          chmod +x alice-renew.sh
          ./alice-renew.sh
